"""Tests for direct identifier scanner.

Validates that the scanner detects known forbidden patterns
and passes on clean content. All test identifiers are synthetic
or loaded from the professor review fixture.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from fenrix_synthetic.qa.direct_identifier_scan import ScanHit, ScanResult, scan_path, scan_zip_entries


FIXTURE_PATH = Path(__file__).resolve().parent.parent / "fixtures" / "professor_review" / "identification_cases.yaml"


@pytest.fixture(scope="module")
def source_data() -> dict[str, list[str]]:
    """Load company/ticker data from the professor review fixture."""
    with open(FIXTURE_PATH) as f:
        data = yaml.safe_load(f)
    sources = data["datasets"]["fenrix_alpha_v2"]["actual_sources"]
    company_names: list[str] = []
    tickers: list[str] = []
    for info in sources.values():
        company_names.append(info["company"])
        tickers.append(info["ticker"])
    return {"company_names": company_names, "tickers": tickers}


def _write_file(base: Path, name: str, content: str) -> Path:
    fp = base / name
    fp.write_text(content, encoding="utf-8")
    return fp


class TestDirectIdentifierScanPatterns:
    """Test that all required pattern classes are detected."""

    def test_detects_cik(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "The CIK for this entity is 0000999999.")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("CIK" in h.pattern_id for h in result.hits)

    def test_detects_commission_file_number(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "Commission File Number: 001-09999")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("commission_file_no" in h.pattern_id for h in result.hits)

    def test_detects_entity_central_index_key(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "EntityCentralIndexKey 0000999999")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("entity_central_index_key" in h.pattern_id for h in result.hits)

    def test_detects_sec_url(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "See https://www.sec.gov/Archives/edgar/data/")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("sec_gov" in h.pattern_id for h in result.hits)

    def test_detects_xbrl_namespace(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.json", '{"ns": "http://xbrl.sec.gov/dei/2024"}')
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("xbrl_sec_gov" in h.pattern_id for h in result.hits)

    def test_detects_ein(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "IRS Employer Identification No. 99-9999999")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("irs_employer_id" in h.pattern_id for h in result.hits)

    def test_detects_cusip(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "CUSIP 999999999")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("cusip" in h.pattern_id for h in result.hits)

    def test_detects_isin(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "ISIN US9999999999")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("isin" in h.pattern_id for h in result.hits)

    def test_detects_dei_namespace(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "dei: DocumentType")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("dei_namespace" in h.pattern_id for h in result.hits)

    def test_detects_us_gaap(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "us-gaap: Assets")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("us_gaap" in h.pattern_id for h in result.hits)

    def test_detects_workiva(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "Generated by Workiva")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("workiva" in h.pattern_id for h in result.hits)

    def test_detects_inline_xbrl(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "This document uses inlineXBRL.")
        result = scan_path(tmp_path)
        assert not result.passed
        assert any("inline_xbrl" in h.pattern_id for h in result.hits)


class TestDirectIdentifierScanClean:
    """Test that clean content passes."""

    def test_passes_clean_markdown(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.md", "# Company Analysis\n\nThis is a clean document about Company 001.\n")
        result = scan_path(tmp_path)
        assert result.passed
        assert result.hits == []

    def test_passes_clean_json(self, tmp_path: Path) -> None:
        _write_file(tmp_path, "test.json", '{"name": "Company 001", "revenue": 5000}')
        result = scan_path(tmp_path)
        assert result.passed


class TestDynamicPatterns:
    """Test that dynamic patterns (from config) are detected."""

    def test_detects_source_company_name(self, tmp_path: Path, source_data: dict[str, list[str]]) -> None:
        names = source_data["company_names"]
        if names:
            _write_file(tmp_path, "test.md", f"This company resembles {names[0]}.")
            result = scan_path(tmp_path, company_names=names)
            assert not result.passed
            assert any("company_name" in h.pattern_id for h in result.hits)

    def test_detects_source_ticker(self, tmp_path: Path, source_data: dict[str, list[str]]) -> None:
        tickers = source_data["tickers"]
        if tickers:
            _write_file(tmp_path, "test.md", f"The ticker {tickers[0]} is blocked.")
            result = scan_path(tmp_path, tickers=tickers)
            assert not result.passed
            assert any("ticker" in h.pattern_id for h in result.hits)


class TestScanResultProperties:
    """Test ScanResult properties."""

    def test_blocking_hits_filtered(self) -> None:
        hits = [
            ScanHit("a", 1, "test", "blocking", "preview"),
            ScanHit("b", 2, "test", "warning", "preview"),
        ]
        result = ScanResult(scanned_files=1, scanned_bytes=100, hits=hits, passed=False)
        assert len(result.blocking_hits) == 1
        assert len(result.warning_hits) == 1

    def test_to_dict(self) -> None:
        hits = [ScanHit("a", 1, "test", "blocking", "preview")]
        result = ScanResult(scanned_files=1, scanned_bytes=100, hits=hits, passed=False)
        d = result.to_dict()
        assert d["total_hits"] == 1
        assert d["blocking_hits"] == 1
        assert not d["passed"]


class TestZipEntryScan:
    """Test ZIP entry name scanning."""

    def test_detects_cik_in_zip_name(self, tmp_path: Path) -> None:
        import zipfile

        zip_path = tmp_path / "test.zip"
        with zipfile.ZipFile(zip_path, "w") as zf:
            zf.writestr("data/CIK_0000999999.txt", "content")
        hits = scan_zip_entries(zip_path)
        assert any("CIK" in h.pattern_id for h in hits)
